### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(KomplexHubModule)
add_subdirectory(KomplexHubContent)
add_subdirectory(KomplexHubPlugin)
add_subdirectory(App)
add_subdirectory(Dependencies)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    KomplexHubModuleplugin
    KomplexHubContentplugin
    KomplexHubPluginplugin
    KomplexHubControlsplugin
    KomplexHubKeroplugin
    Qt6::Quick
    Qt6::Core
    Qt6::Gui
    Qt6::Qml
    Qt6::QuickControls2
)