#ifndef KOMPLEX_GLOBAL_H
#define KOMPLEX_GLOBAL_H

#ifdef KOMPLEX_PLUGIN
#define KOMPLEX_EXPORT Q_DECL_EXPORT
#else
#define KOMPLEX_EXPORT Q_DECL_IMPORT
#endif

#define SLIDING_CACHE_WINDOW_SIZE 100
#define SLIDING_CACHE_PREFETCH_THRESHOLD 20

#define NETWORK_TIMEOUT 10000

#endif // KOMPLEX_GLOBAL_H
